### ISSUE TITLE
zero accuracy

### ISSUE THREAD

**Issue by TengliEd** [auroua/InsightFace_TF#13]
I trained your post r50 model from scratch on ms1m dataset (run train_nets.py). After one epoch (170k steps), the printed training accuracy is still 0.000000.

**Comment by auroua** [comment]
Please reference this issue https://github.com/auroua/InsightFace_TF/issues/10

**Comment by TengliEd** [comment]
Thanks @auroua. I just found the network checkpoint was so big (1.7G). why?

**Comment by TengliEd** [comment]
![screen shot 2018-04-16 at 11 50 22 am](https://user-images.githubusercontent.com/15106660/38789376-6ccdac90-416c-11e8-967c-d6cdd00b3d50.png)
I just found there are 14 units in block3.

**Comment by auroua** [comment]
This bug about zero accuracy have fixed. Please pull the new code.
