### ISSUE TITLE
How to test whether two images are identical face?

### ISSUE THREAD

**Issue by mlight3** [auroua/InsightFace_TF#15]
Hello. First, thanks for good projects! 👍 

I cloned it and download pretrained "model A".
But I wonder how to test whether two images are identical face?

Here is my code.
```
sess = tf.Session()    
saver = tf.train.import_meta_graph('./pretrained_models/InsightFace_iter_1060000.ckpt.meta')
saver.restore(sess, './pretrained_models/InsightFace_iter_1060000.ckpt')

input_images = tf.get_default_graph().get_tensor_by_name('img_inputs:0')

image = Image.open('./test_image.jpg')
image = image.resize((112, 112))

images = [np.array(image)]

outputs = sess.run('arcface_loss/embedding_weights:0', feed_dict={input_images: images})    
```

But the output shape is always (512, 85164)

Would you let me know how to test images?
Thanks!

**Comment by auroua** [comment]
Please reference  `eval_ckpt_file.py`.

**Comment by iamrishab** [comment]
> Hello. First, thanks for good projects! 👍
> 
> I cloned it and download pretrained "model A".
> But I wonder how to test whether two images are identical face?
> 
> Here is my code.
> 
> ```
> sess = tf.Session()    
> saver = tf.train.import_meta_graph('./pretrained_models/InsightFace_iter_1060000.ckpt.meta')
> saver.restore(sess, './pretrained_models/InsightFace_iter_1060000.ckpt')
> 
> input_images = tf.get_default_graph().get_tensor_by_name('img_inputs:0')
> 
> image = Image.open('./test_image.jpg')
> image = image.resize((112, 112))
> 
> images = [np.array(image)]
> 
> outputs = sess.run('arcface_loss/embedding_weights:0', feed_dict={input_images: images})    
> ```
> 
> But the output shape is always (512, 85164)
> 
> Would you let me know how to test images?
> Thanks!

Can you please share the pretrained weights you have used via Google Drive?

**Comment by PPPPPPPeng** [comment]
> 
> 
> Hello. First, thanks for good projects! 👍
> 
> I cloned it and download pretrained "model A". But I wonder how to test whether two images are identical face?
> 
> Here is my code.
> 
> ```
> sess = tf.Session()    
> saver = tf.train.import_meta_graph('./pretrained_models/InsightFace_iter_1060000.ckpt.meta')
> saver.restore(sess, './pretrained_models/InsightFace_iter_1060000.ckpt')
> 
> input_images = tf.get_default_graph().get_tensor_by_name('img_inputs:0')
> 
> image = Image.open('./test_image.jpg')
> image = image.resize((112, 112))
> 
> images = [np.array(image)]
> 
> outputs = sess.run('arcface_loss/embedding_weights:0', feed_dict={input_images: images})    
> ```
> 
> But the output shape is always (512, 85164)
> 
> Would you let me know how to test images? Thanks!

Have you resolve this problem? I want to compare two faces's dist to determine whether two images are identical face,too!
