### ISSUE TITLE
unzip error of ckpt_model_b.zip 

### ISSUE THREAD

**Issue by cznc** [auroua/InsightFace_TF#16]
Hi,
 I got an error when I unzip the file ckpt_model_b.zip which was downloaded from Baidu Wangpan:
    F:\BaiduNetdiskDownload\ckpt_model_b(1).zip: 文件 F:\BaiduNetdiskDownload\ckpt_model_b(1)\InsightFace_iter_1100000.ckpt.data-00000-of-00001 里出现校验和错误。该文件已损坏。
    F:\BaiduNetdiskDownload\ckpt_model_b(1).zip: 压缩文件已损坏
I downloaded again and again, but it was the same.

**Comment by hxl1990** [comment]
I get the same error with you

**Comment by auroua** [comment]
I have uploaded two new file, you can down load the new file.
