### ISSUE TITLE
Not Found Error in Model D Checkpoint (710K)

### ISSUE THREAD

**Issue by Neltherion** [auroua/InsightFace_TF#32]
I get this error when trying to run `eval_ckpt_file.py`:

```
NotFoundError (see above for traceback): Key resnet_v1_50/block1/unit_1/bottleneck_v1/shortcut_bn/BatchNorm/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_79 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_84_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```

**Comment by david-di** [comment]
Is here anyone could solve this problem?
I met a similar Error, resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/kernel not found in checkpoint

I use TF 1.9.0 and TL 1.8.5

**Comment by zsz00** [comment]
I met a similar Error

**Comment by david-di** [comment]
Change your Tensorflow and Tensorlayer version to satisfied the requirements of this project, that error would disappear.

**Comment by kinraymon** [comment]
@david-di  
I use Tensorflow1.6 and Tensorlayer 1.7 version,still got this error
Could you show me your version list?

**Comment by zijing-wu** [comment]
I had the similar error with model A (Tensorflow 1.4 and Tensorlayer 1.7). The error disappeared when I switched to model C. I haven't figured out why though.

**Comment by TimLiujn** [comment]
@Neltherion have you solved this problem

**Comment by hoangdzung** [comment]
@zijing-wu  Could you share the model A, B and C (through Google Drive)? I can't download them from Baidu because I don't know to use Baidu and it's quite complex.
