### ISSUE TITLE
verification.py

### ISSUE THREAD

**Issue by ymcasky** [auroua/InsightFace_TF#4]
Hi, thanks for your work!
I found a bug in your code.
In verification.py->test 
data-=127.5
data *= 0.0078125
you have to use copy so datas won't change simultaneously.

Here is the example:
```
for idx, data in enumerate(data_iter(datas, batch_size)):
            if idx%100==0:
              print('idx=',idx)
            data_2 = data.copy()
            data_2 -= 127.5
            data_2 *= 0.0078125
            feed_dict[input_placeholder] = data_2
```

**Comment by auroua** [comment]
Thanks!
I have fixed the bug. I will push it right now.
