### ISSUE TITLE
请问 mm = sin_m * m

### ISSUE THREAD

**Issue by dl8207531** [auroua/InsightFace_TF#51]
sin_m = math.sin(m)
mm = sin_m * m
我看原作者代码是mm = math.sin(math.pi-m)*m 请问这是有什么原因吗？

**Comment by Imtinan1996** [comment]
`math.sin(math.pi-m)*m` and `mm = sin_m * m` 

give you the same result

**Comment by dl8207531** [comment]
math.sin(math.pi-m)*m == math.sin(m)*m?
I still don't understand what it means. Can you explain it in detail?

**Comment by Imtinan1996** [comment]
sin(pi-0.5)*0.5 = 0.2397127693
sin(0.5)*0.5 = 0.2397127693

You can look into the mathematical explanation for this :)

**Comment by dl8207531** [comment]
I see now. Thank you for your answer.
