### ISSUE TITLE
Is the testing not using the Cosine distance of two feature vectors?

### ISSUE THREAD

**Issue by yxd117** [auroua/InsightFace_TF#58]
It seems that the the testing distance used is L2 distance. And the threshold is set between [0, 4]. Is there any reason to use this other than Cosine distance?

**Comment by yxd117** [comment]
@auroua

**Comment by david-di** [comment]
The distance used in code is equivalent to Cosine distance, square(L2) = 2 * (1 - Cos). Notice that, features were normalized.

**Comment by yxd117** [comment]
Thanks I got it. After normalization, these two are equivalent.
