### ISSUE TITLE
ModuleNotFoundError: No module named 'tl_layers_modify'

### ISSUE THREAD

**Issue by zhanglaplace** [auroua/InsightFace_TF#65]
running train_nets_mgpu_new.py 后出现这个问题，nets下有tl_layers_modify文件。请教下如何解决

**Comment by Vincent630** [comment]
i think that is because the path problem,maybe you can add these two lines to fix this problem:
import sys 
sys.path.append('the absolute path of the script named tl_layers_modify')

**Comment by yunkchen** [comment]
from .tl_layers_modify import ，that could work on python3

**Comment by zhanglaplace** [comment]
@Vincent630 @yunkchen Thanks ，they all work.
