### ISSUE TITLE
test the acc of model c on the lfw?

### ISSUE THREAD

**Issue by flyduck** [auroua/InsightFace_TF#85]
在 模型里面没有checkpoint，不能运行测试程序啊，为什么不提供checkpoint呢？或者直接提供生成的freez图啊？

**Comment by zfs1993** [comment]
checkpoint 里面不就是一个名字嘛，自己照着别的造一个就行呀，大兄弟

**Comment by flyduck** [comment]
@zfs1993 嗯嗯，谢谢！我改好了，模型载入没有问题了，我测试了model_c，在lfw数据集上平均准确率只有%91.9左右，不知道是什么原因，我用的是tensorflow==1.12的，然后原代码中是一次性把所有的测试图像都读入进去了，我改成了一次性只读10张图像，要不然内存装不下。最后结果和作者发布的差很多啊，你测试结果是什么啊？
