### ISSUE TITLE
训练代码 train_nets.py 内存泄漏

### ISSUE THREAD

**Issue by Dawning23** [auroua/InsightFace_TF#86]
随着训练的进行，cpu memory 占用率越来越高（使用 gpu 训练），注释掉 validate，summary，log_file  部分后依然有此问题。如果该服务器下还有其他人训练，会严重减慢别人的训练速度，请问有人遇到这个问题么？

Google Transla：
As the training progresses, the cpu memory usage is getting higher and higher (using gpu training), and there is still this problem after commenting out the validate, summary, and log_file sections. If there are other people training under the server, it will seriously slow down the training speed of others. Does anyone encounter this problem?

**Comment by zfs1993** [comment]
我好想也遇到了，在Shuffle buffer filled这里就卡住了，然后内存占用会一直上升，真是见鬼了

**Comment by meitianjinbu** [comment]
内存不断上升，一样的问题。你们解决有进展不？

**Comment by zfs1993** [comment]
我这里是gpu没有调起来，导致内存不够了，gpu用起来了就好了

**Comment by meitianjinbu** [comment]
> 我这里是gpu没有调起来，导致内存不够了，gpu用起来了就好了

你看关注下,我的gpu用起来了,内存也会不断上升,当然上升的不是很快.基本上20000step后就挂掉了.

**Comment by lovejing0306** [comment]
> > 我这里是gpu没有调起来，导致内存不够了，gpu用起来了就好了
> 
> 你看关注下,我的gpu用起来了,内存也会不断上升,当然上升的不是很快.基本上20000step后就挂掉了.

我也遇到了这个问题，请问你解决了么？

**Comment by Dawning23** [comment]
> 我这里是gpu没有调起来，导致内存不够了，gpu用起来了就好了

使用 watch -n 1 nvidia-smi 命令查看可以确定 GPU 已经用起来了，但是依然存在内存泄漏问题

**Comment by lovejing0306** [comment]
我就是的，我能看到我的GPU内存已经是跑满了，然后突然就报错了“ResourceExhaustedError (see above for traceback): OOM when allocating tensor”，你的也是这个样子吗？

> > 我这里是gpu没有调起来，导致内存不够了，gpu用起来了就好了
> 
> 使用 watch -n 1 nvidia-smi 命令查看可以确定 GPU 已经用起来了，但是依然存在内存泄漏问题

**Comment by lovejing0306** [comment]
我不断减小我的batch，最后跑起来了 @Dawning23

**Comment by lovejing0306** [comment]
想问下，你一个批次设置了几张图片那？

Dawning23 <notifications@github.com>于2019年7月12日 周五下午4:31写道：

**Comment by fcs203** [comment]
dataset = tf.data.TFRecordDataset(tfrecords_f)
dataset = dataset.shuffle(buffer_size=args.buffer_size)
dataset = dataset.map(parse_function)
dataset = dataset.batch(args.batch_size)
dataset = dataset.prefetch(1)
iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()

This works
